# Generated by Django 2.2.6 on 2019-10-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirillis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
