# Generated by Django 2.2.6 on 2019-10-21 14:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mirillis', '0006_auto_20191021_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
