# Generated by Django 2.2.6 on 2019-10-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirillis', '0007_auto_20191021_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
